FROM python:3.10-buster

RUN apt-get update && apt-get install -y \
    pandoc default-jre graphviz \
    texlive-latex-recommended \
    texlive-latex-extra \
    texlive-fonts-recommended \
    latexmk

WORKDIR /app
COPY . .

RUN python -m pip install --upgrade pip

RUN pip install sphinx-book-theme==1.1.3 --index-url https://pypi.org/simple --retries 5 --default-timeout=1000
RUN pip install ipython==8.26.0 --index-url https://pypi.org/simple --retries 5 --default-timeout=1000
RUN pip install jupyter==1.0.0 --index-url https://pypi.org/simple --retries 5 --default-timeout=1000
RUN pip install myst-parser==4.0.0 --index-url https://pypi.org/simple --retries 5 --default-timeout=1000
RUN pip install nbsphinx==0.9.5 --index-url https://pypi.org/simple --retries 5 --default-timeout=1000
RUN pip install sphinx-autobuild==2024.4.16	--index-url https://pypi.org/simple --retries 5 --default-timeout=1000
RUN pip install sphinx-copybutton==0.5.2 --index-url https://pypi.org/simple --retries 5 --default-timeout=1000
RUN pip install sphinx-markdown-tables==0.0.17 --index-url https://pypi.org/simple --retries 5 --default-timeout=1000
RUN pip install sphinx-panels==0.4.1 --index-url https://pypi.org/simple --retries 5 --default-timeout=1000
RUN pip install sphinxcontrib-plantuml==0.30 --index-url https://pypi.org/simple --retries 5 --default-timeout=1000

CMD sphinx-autobuild --host 0.0.0.0  docs/ docs/_build/html

# Build:
# $ docker build -f Dockerfile.docs -t dsms-sdk-docs .

# Run:
# $ docker run -it --rm -v $PWD:/app -p 8000:8000 dsms-sdk-docs
