FROM python:3.10-buster

RUN apt-get update && apt-get install -y \
    pandoc default-jre graphviz \
    texlive-latex-recommended \
    texlive-latex-extra \
    texlive-fonts-recommended \
    latexmk

WORKDIR /app
COPY . .

RUN python -m pip install --upgrade pip

RUN pip3 install -r requirements.txt

CMD sphinx-autobuild --host 0.0.0.0  docs/ docs/_build/html

